from __future__ import annotations

import json
import logging
import os
import re
import traceback
from typing import Any

import httpx

from backend.agent.prompt_templates import build_insight_prompt


class InsightGenerationError(Exception):
    pass

logger = logging.getLogger(__name__)

def _normalize_text(text: str) -> str:
    cleaned = re.sub(r"\s+", " ", text).strip()
    # Remove repeated sentence tails like "... ...".
    cleaned = re.sub(r"([.!?])\1+", r"\1", cleaned)
    # Keep concise.
    if len(cleaned) > 420:
        cleaned = cleaned[:420].rsplit(" ", 1)[0].rstrip(".") + "."
    return cleaned


def _numbers_from_text(text: str) -> set[str]:
    return set(re.findall(r"-?\d+(?:\.\d+)?", text))


def _numbers_from_results(results: dict[str, Any]) -> set[str]:
    blob = json.dumps(results, ensure_ascii=False)
    return set(re.findall(r"-?\d+(?:\.\d+)?", blob))


def _format_currency(val: float | None) -> str:
    if val is None:
        return "₹0"
    return f"₹{round(val):,}"

def _format_percent(val: float | None) -> str:
    if val is None:
        return "0%"
    return f"{round(val, 1)}%"

def _format_dict_values(results: dict[str, Any]) -> dict[str, Any]:
    formatted = {}
    for k, v in results.items():
        if isinstance(v, (int, float)):
            if "percent" in k.lower():
                formatted[k] = _format_percent(v)
            else:
                formatted[k] = _format_currency(v)
        else:
            formatted[k] = v
    return formatted

def _fallback_insight(analysis_type: str, results: dict[str, Any]) -> str:
    fmt = _format_dict_values(results)
    if analysis_type == "diagnostic":
        change = fmt.get("change_percent", "0%")
        top = fmt.get("top_contributor", "unknown")
        return (
            f"Diagnostic findings indicate a change of {change}."
            + (f" The primary contributor is {top}." if top else "")
        )
    if analysis_type == "comparison":
        a = fmt.get("entity_a", "A")
        b = fmt.get("entity_b", "B")
        diff = fmt.get("difference", "₹0")
        return f"Comparison findings show {a} versus {b} with a difference of {diff}."
    if analysis_type == "forecast":
        p = fmt.get("predicted_revenue", "₹0")
        period = fmt.get("forecast_period", "next period")
        if period == "next_period":
            period = "next month"
        return f"Revenue is projected to reach approximately {p} {period}."
    if analysis_type == "ranking":
        top_region = results.get("top_region")
        top_product = results.get("top_product")
        # Find the metric value key (anything that isn't top_region/top_product)
        metric_key = next((k for k in results if k not in ("top_region", "top_product")), None)
        metric_val = fmt.get(metric_key, "₹0") if metric_key else "₹0"
        metric_label = metric_key.replace("_", " ") if metric_key else "value"
        if top_region:
            return f"The highest {metric_label} was generated by {top_region} at {metric_val}."
        if top_product:
            return f"The highest {metric_label} was generated by {top_product} at {metric_val}."
        return f"Ranking analysis completed with top {metric_label} of {metric_val}."
    if analysis_type == "trend":
        return "Trend analysis shows the revenue trajectory over the selected periods."
    return f"{analysis_type.capitalize()} findings are based on the provided analytics results."


def generate_insight(analysis_type: str, results: dict[str, Any]) -> str:
    fmt_results = _format_dict_values(results)
    ollama_base = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434").rstrip("/")
    model = os.getenv("OLLAMA_MODEL", "phi3:latest")
    prompt = build_insight_prompt(analysis_type, fmt_results)
    url = f"{ollama_base}/api/generate"
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.2},
    }

    logger.info(
        "Ollama InsightGenerator request url=%s model=%s analysis_type=%s",
        url,
        model,
        analysis_type,
    )
    logger.info("Ollama InsightGenerator payload=%s", json.dumps(payload, ensure_ascii=False))

    try:
        with httpx.Client(timeout=45.0) as client:
            resp = client.post(url, json=payload)
    except httpx.RequestError as exc:
        logger.exception("Ollama InsightGenerator request exception")
        raise InsightGenerationError(f"Unable to reach Ollama at {url}. Details: {exc}") from exc

    logger.info("Ollama InsightGenerator response status=%s", resp.status_code)
    logger.info("Ollama InsightGenerator response body=%s", resp.text)

    if resp.status_code >= 400:
        raise InsightGenerationError(
            f"Ollama request failed with status {resp.status_code}. body={resp.text}"
        )

    try:
        payload = resp.json()
    except json.JSONDecodeError as exc:
        logger.error(
            "Ollama InsightGenerator JSON decode error traceback=%s",
            traceback.format_exc(),
        )
        raise InsightGenerationError("Ollama returned invalid JSON.") from exc

    raw_text = payload.get("response")
    if not isinstance(raw_text, str) or not raw_text.strip():
        return _fallback_insight(analysis_type, results)

    insight = _normalize_text(raw_text)
    if not insight:
        return _fallback_insight(analysis_type, results)

    # Guardrail: avoid introducing unseen numeric claims.
    insight_nums = _numbers_from_text(insight)
    result_nums = _numbers_from_results(results)
    if not insight_nums.issubset(result_nums):
        return _fallback_insight(analysis_type, results)

    return insight
